pages/list-of-vaccination-locations.md

Update file: list-of-vaccination-locations.md

---

pages/faq.md

Update file: faq.md

---

pages/how-to-sign-up.md

Removed wordings on the "phases"

changes on the "how to sign up" section

---

_locations/2-vaccination-centres.md

add 5 more vaccination center for 18 feb 2021

Updates of Vaccination Centre on 18 feb

---

_locations/2-vaccination-centres.md
pages/how-to-sign-up.md

removed the wordings relates to pilot launch

updates on how to sign up

---

pages/how-to-sign-up.md

updates of how to sign up

---

index.md

change from register your interest to register here

updates of wording at the hero section

---

_locations/2-vaccination-centres.md

added 3 new vaccination centre

added new vaccination centre

---

pages/faq.md

change of FAQ on reschedule of appointment

---

_locations/2-vaccination-centres.md

updated Centre / clubs as per PA request

Updates of community center naming 

---

_locations/2-vaccination-centres.md

updated VC name

---

_locations/2-vaccination-centres.md

Update VC names

---

index.md
pages/how-to-sign-up.md

updated in the hero session and the sign up page

updates of age

---

pages/faq.md

updated FAQ

---

pages/health-advisory.md

updated the health advisory

---

pages/appeal-for-early-vaccination.md

Update file: appeal-for-early-vaccination.md

---

index.md
pages/how-to-sign-up.md

update age band

---

_config.yml

Google Analytics ID: UA-191846183-3

Google Analytics for vaccine.gov.sg

---

_locations/2-vaccination-centres.md

updated vaccination centre vaccine type

---

_locations/0-clinics.md
_locations/1-polyclinics.md
_locations/2-vaccination-centres.md

updated VC location 

---

_locations/1-polyclinics.md
_locations/2-vaccination-centres.md

updated format

---

index.md
pages/faq.md

update of FAQ

---

pages/how-to-sign-up.md

Update file: how-to-sign-up.md

---

pages/faq.md
pages/health-advisory.md

update of age band for 40 years and above

update of age band

---

_locations/vaccination-centres.md

Update file: vaccination-centres.md

---

pages/health-advisory.md
pages/how-to-sign-up.md

update of new age band

---

pages/health-advisory.md

Update file: health-advisory.md

---

pages/health-advisory.md

updated link for FAQ

---

pages/faq.md
pages/health-advisory.md

update of pfizer name

---

pages/faq.md
pages/health-advisory.md

add Comirnaty

---

_locations/polyclinics.md

Update file: polyclinics.md

---

_locations/collection.yml
_locations/mobile-vaccination-team.md

added new location - mvt

---

_locations/clinics.md

Update file: clinics.md

---

_locations/vaccination-centres.md

Reverts isomerpages/moh-vaccinegov#137

Revert "Update file: vaccination-centres.md"

---

_locations/mobile-vaccination-team.md

Reverts isomerpages/moh-vaccinegov#158

Revert "update to mobile vacc"

---

index.md

Reverts isomerpages/moh-vaccinegov#157

Revert "updated child vacc"

---

index.md

Reverts isomerpages/moh-vaccinegov#165

Revert "gitch on index"

---

index.md

Reverts isomerpages/moh-vaccinegov#172

Revert "glitch - index "

---

_locations/polyclinics.md

fixing an error

---

_locations/polyclinics.md

polyclinic change timing

---

pages/health-advisory.md

consent form change link

---

_locations/Private Vaccination Programme.md

removed email

---

_locations/polyclinics.md

polyclinic consolidation

---

pages/Get Vaccinated.md

updated website

---

_locations/polyclinics.md

correcting an error for polyclinics

---

_locations/Private Vaccination Programme.md

…:"Private Vaccination Programme.md","userId":"1058"}

pfizer bivalent to monovalent

---

_locations/polyclinics.md

Change in polyclinic page to include in the event of high demand, MOPs may be advised to return another day

---

_locations/polyclinics.md

Change in polyclinic operating hours

---

_locations/polyclinics.md

Update Geylang polyclinic operating hours

---

_locations/polyclinics.md

Change in polyclinics opening hours

---

_locations/polyclinics.md

Change in polyclinics description 

---

_locations/Joint Testing & Vaccination Centres (Vaccination Wing).md

…tion Wing).md","fileName":"Joint Testing & Vaccination Centres (Vaccination Wing).md","userId":"3540"}

Change in JTVC

---

_locations/polyclinics.md

Changes in Polyclinic Timing

---

_locations/Joint Testing & Vaccination Centres (Vaccination Wing).md

…tion Wing).md","fileName":"Joint Testing & Vaccination Centres (Vaccination Wing).md","userId":"3540"}

Changes in JTVCs Operating Hours

---

_locations/Joint Testing & Vaccination Centres (Vaccination Wing).md

…tion Wing).md","fileName":"Joint Testing & Vaccination Centres (Vaccination Wing).md","userId":"3540"}

Changes in JTVC Operation Hours (align with weekdays)

---

_locations/Private Vaccination Programme.md

…:"Private Vaccination Programme.md","userId":"3540"}

Removal of Raffles Executive Medical Centre from PVP

---

_locations/Joint Testing & Vaccination Centres (Vaccination Wing).md

…tion Wing).md","fileName":"Joint Testing & Vaccination Centres (Vaccination Wing).md","userId":"3540"}

Update of Information on JTVCs

---

_locations/Private Vaccination Programme.md

…:"Private Vaccination Programme.md","userId":"3540"}

Removal of 5 PVP clinics as offboard since 19/7/24

---

_locations/Private Vaccination Programme.md

…:"Private Vaccination Programme.md","userId":"3540"}

Removal of Primary Care Asia under PVP

---

_locations/polyclinics.md

Change in Bukit Panjang Polyclinic Operating Hours

---

pages/faq.md

Remove the word additional dose.

{"message":"Update file: faq.md","fileName":"faq.md","userId":"41436"}

---

_locations/Joint Testing & Vaccination Centres.md
_locations/Private Vaccination Programme.md
_locations/polyclinics.md

Change back to XBB as the change for now as JN1 vaccine only available on Monday. Over the weekend still XBB.

Change back the location segment back to XBB

---

_locations/Joint Testing & Vaccination Centres.md
_locations/Private Vaccination Programme.md
_locations/polyclinics.md

Changes to JN.1 to all locations, to be implement after 9pm.

JN.1 update to the locations (approve after 9pm)

---

_locations/mobile-vaccination-team.md

Updating MVT link

---

_locations/Private Vaccination Programme.md

Fullerton clinic has withdraw from PVP and will onboard NVP.

Remove Fullerton clinic from PVP

---

pages/beware-of-scam.md

Updating COVID hotline on "Beware of Scam" page

---

_locations/mobile-vaccination-team.md

…le-vaccination-team.md","userId":"3540"}

Updating link to MVT schedule

---

_locations/mobile-vaccination-team.md

…le-vaccination-team.md","userId":"3540"}

Update in MVT operating hours
